### ISSUE TITLE
Cannot find module  '../build/Release/node_sqlite3.node'

### ISSUE THREAD

**Issue by lucj** [mapbox/node-sqlite3#91]
I'm working with node 0.8.4, and installed node-sqlite3 version 2.1.5  
npm did not complain but when I run the simple example (the one in the README file) I got the following error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '../build/Release/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/gp/test/node_modules/sqlite3/lib/sqlite3.js:1:104)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

Any idea of the problem ?
