### ISSUE TITLE
 v3.0.5 doesn't work on Windows 7 / 32 bits with node 0.12.X

### ISSUE THREAD

**Issue by 10mitri** [mapbox/node-sqlite3#438]
I have tried v3.0.5 on Windows 7 / 32 bits. It works very well with node 0.10.36.
But doesn't work with node 0.12.X.

The first connection launches the error :  

>module.js:338
>    throw err;
 >         ^
>Error: Cannot find module 'C:\node.js\node_modules\sqlite3\lib\binding\node-v14-win32-ia32\node_sqlite3.node'
>    at Function.Module._resolveFilename (module.js:336:15)
>    at Function.Module._load (module.js:278:25)
>    at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at Object.<anonymous> (C:\node.js\node_modules\sqlite3\lib\sqlite3.js:4:15)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Module.require (module.js:365:17)

The directory ..\binding\node-**v14**-win32-ia32\ doesn't exist,
but I find the file node_sqlite3.node in the directory ..\binding\node-**v11**-win32-ia32.

Changing the directory name ...**v11** to **v14** just does : 

>module.js:355
>  Module._extensions\[extension\](this, filename);
>                               ^
>Error: La procédure spécifiée est introuvable.
> C:\node.js\node_modules\sqlite3\lib\binding\node-v14-win32-ia32\node_sqlite3.node
>    at Error (native)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)
>    at Module.require (module.js:365:17)
>    at require (module.js:384:17)
>    at Object.<anonymous> (C:\node.js\node_modules\sqlite3\lib\sqlite3.js:4:15)
>    at Module._compile (module.js:460:26)
>    at Object.Module._extensions..js (module.js:478:10)
>    at Module.load (module.js:355:32)
>    at Function.Module._load (module.js:310:12)

**Comment by sandorfr** [comment]
Same issue here I tried a few things such as renaming the directory (which doesn't work).

**Comment by springmeyer** [comment]
Keep in mind that `npm install` installs binaries for your specific node version, arch, and operating system. If you change node versions you need to run `npm install` again. It sounds like the problem is that you need to re-run `npm install`. Please do not rename directories: that will not work.

**Comment by sandorfr** [comment]
This is occurring on a fresh install (no priori node_module).

**Comment by springmeyer** [comment]
@sandorfr you did not share your error message. it might be different so I'll need to see the entire message.

**Comment by sandorfr** [comment]
In fact it was exactly the same but : 
I was using a 0.10.32 version of node. I upgraded to 0.12.0 (removed node_modules and run npm install) and now it works fine.

**Comment by 10mitri** [comment]
I reinstalled al but had a new error. 
I eventualy found the solution. I use the binary version of node (not with installer). At a moment in the npm process node.exe wasn't found anymore. So I added the path of node.exe to %PATH%, and so the update worked. After this, node 0.12.2 and sqlite3 3.0.5 do it well on Windows7.
