### ISSUE TITLE
Build for nw.js v0.12.3 in order to use child_process.fork ?

### ISSUE THREAD

**Issue by hems** [mapbox/node-sqlite3#521]
Hello Guys,

It seems that nw.js is closing this issue https://github.com/nwjs/nw.js/issues/213 which allows nw.js apps fork child_process which are very useful when doing huge SQLite queries - which still freezing my UI when running on node-webkit 0.8.6.

Any chance we could get it working with v0.12.3 ?

Or Is there any documented workaround in order to perform the query in background without freezing the GUI ?

Thank you!

**Comment by TwanoO67** [comment]
HI @hems,

Doc suggest to do:

        npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.12.3

But it doesn't seem to work on my installation. 
Maybe an outdated version of nw.js and/or sqlite3 would run better?

**Comment by hems** [comment]
@TwanoO67 i have it working with 0.8.6, and it seems that sqlite supports also 0.10, but this child_process.fork issue seems to be solved on 0.12.

I might be wrong, to be honest this still a bit confusing for me, but it seems that for some reason sqlite3 module would have to "officially support" 0.12 in order for it to work.

**Comment by rbfowler9lfc** [comment]
I've been able to build it correctly for nw.js 0.12.3 with the npm command from the docs as @TwanoO67 suggested. Is your installed node version the same as nw.js 0.12.3 is built upon (io.js 1.2.0 IIRC)?
Anyway, prior to upgrading to 0.12.3 I was using 0.9.2 and although cp.fork was still broken, you could use cp.spawn with options.stdio = [null, null, null, 'ipc'] and get the same process.send() functionality as in cp.fork, @hems

**Comment by hems** [comment]
@rbfowler9lfc thanks a lot for the tip! i'll have a better look at that asap!

thanks!

**Comment by hems** [comment]
@rbfowler9lfc 
Using nvm i switched to iojs-1.2, deleted my node_modules. 

did a npm install to get all dependencies, after that i build only sqlite with
````
npm install sqlite3 --build-from-source --runtime=node-webkit --target_arch=x64 --target=0.12.3
````

It builds OK and all seems fine, but then when opening my app using nw.js version 0.12.3 I still i get this error:

[3819:1108/005039:ERROR:nw_shell.cc(336)] Error: Cannot find module '/Volumes/[...]/app/node_modules/sqlite3/lib/binding/node-webkit-v0.12.3-darwin-ia32/node_sqlite3.node'

**Comment by hems** [comment]
Actually was my bad, i was using the 32 version of nw.js so i had to tweak the target_arch to "ia32", which is the one my nw.js file was complaining about.

will do some more tests but it seems to be OK

**Comment by hems** [comment]
Now i get the error:

````
[5364:1108/005947:ERROR:nw_shell.cc(336)] Error: SQLITE_CANTOPEN: unable to open database file
  at Error (native)
````

Which i wasn't getting with the previous build i was using with node-webkit 0.8.6..

need to investigate what is going on //=

**Comment by hems** [comment]
Now when i do 
````
sqlite = new sqlite3.Database path
````

to an non-existing path this error is thrown and the application fails to continue, while before it was being automatically created when i did that.

maybe this behaviour changed in one of the last updates? weird //=

**Comment by hems** [comment]
then if i use
```
sqlite = new sqlite3.Database( path, sqlite3.OPEN_CREATE )
````
i get

````
[5742:1108/010748:ERROR:nw_shell.cc(336)] Error: SQLITE_MISUSE: out of memory
  at Error (native)
````

**Comment by tmcw** [comment]
nwjs is not yet supported, main ticket is #497
