### ISSUE TITLE
fails to build on FreeBSD 11.1 x64 under node 10.1

### ISSUE THREAD

**Issue by dBitech** [mapbox/node-sqlite3#995]
> sqlite3@3.1.13 install /usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-freebsd-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.1.0 (node-v64 ABI) (falling back to source compile with node-gyp)
gmake: Entering directory '/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/darcy/.node-gyp/10.1.0/include/node/node.h:172:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/darcy/.node-gyp/10.1.0/include/node/node.h:165:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/darcy/.node-gyp/10.1.0/include/node/node.h:158:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/home/darcy/.node-gyp/10.1.0/include/node/node.h:172:50: note: 'MakeCallback' has been explicitly marked deprecated here
                NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                 ^
../src/database.cc:144:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:525:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:625:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
8 warnings and 1 error generated.
gmake: *** [node_sqlite3.target.mk:115: Release/obj.target/node_sqlite3/src/database.o] Error 1
gmake: Leaving directory '/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/build'
gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p10
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64"
gyp ERR! cwd /usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp ERR! System FreeBSD 11.1-RELEASE-p10
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/usr/home/darcy/tmp/node_modules/@mapbox/mbtiles/node_modules/sqlite3/lib/binding/node-v64-freebsd-x64' (1)
npm WARN enoent ENOENT: no such file or directory, open '/usr/home/darcy/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by springmeyer** [comment]
Please try out the v4.0.1 release https://github.com/mapbox/node-sqlite3/blob/master/CHANGELOG.md#401 and create a new ticket if you are still having issues.
