### ISSUE TITLE
Error When Requiring Sqlite3

### ISSUE THREAD

**Issue by jcrosby10** [mapbox/node-sqlite3#1080]
I have installed and built sqlite3 and when I use `require(sqlite3).verbose()` I get the following error:
*Cannot find module '.../node_modules/sqlite3/package.json*. I'm not sure what is going on here as the package.json file is actually there. Has anyone seen this before and know how to get it working?

node: 8.12.0
sqlite3: 4.0.4
electron: 2.0.13
Working on Mac OS High Sierra 10.13.6

**Comment by jcrosby10** [comment]
Its crashing on this line in sqlite3.js
`var binding_path = binary.find(path.resolve(path.join(__dirname,'../package.json')));`

**Comment by kewde** [comment]
Hi,
Could you create a simple reproducible test case, preferably something I can git clone?
Thank you.

**Comment by kewde** [comment]
Hi,

I independently found the issue too, rebuild should resolve the issue you had with finding the right binary.
Could you provide a reproducible testcase, that would help me greatly in understanding and debugging the issue. 
Thanks.

**Comment by kewde** [comment]
better-sqlite3 != node-sqlite3 btw

**Comment by jcrosby10** [comment]
That was a mistype, should be sqlite3 not better-sqlite3. I did find a solution to this however. In order to require a native node module like sqlite3 I have to use`__non_webpack_require__`. In case anyone else has this problem. https://webpack.js.org/configuration/node/#other-node-core-libraries

**Comment by kdym** [comment]
> That was a mistype, should be sqlite3 not better-sqlite3. I did find a solution to this however. In order to require a native node module like sqlite3 I have to use`__non_webpack_require__`. In case anyone else has this problem. https://webpack.js.org/configuration/node/#other-node-core-libraries

You said you were using Quasar and was able to make it work using **__non_webpack_require__**.

Where can I put this command to make it work? In **quasar.conf.js?**
