### ISSUE TITLE
node searching in 'node-v11-darwin-x64', fails to find 'node_sqlite3.node'

### ISSUE THREAD

**Issue by charlesjdimino** [mapbox/node-sqlite3#228]
STR:

```
$ cd ~ 
$ mkdir -p tmp && cd tmp
$ npm install node-gyp && cd node_modules
$ git clone git@github.com:mapbox/node-sqlite3.gi && cd node-sqlite3
$ node ../node-gyp/bin/node-gyp.js configure build && cd ../..
$ node 
```

``` js
> var sqlite3 = require('sqlite3');

 Error: Cannot find module './binding/Release/node-v11-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/diminoten/tmp/node_modules/node-sqlite3/lib/sqlite3.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)     
    at Module.require (module.js:364:17)
```

I'm not entirely sure I'm doing this the way it's intended, was hoping to get some guidance.  I do need to build it myself from source, though, and not pull it from github or npm.

This worked in <=v2.1.15.  Only noticed it when I tried to upgrade today.

**Comment by mattfrey** [comment]
This issue is still occurring for me using OS X Yosemite with Node 0.11.14 and sqlite3 1.0.8
```
Error: Cannot find module '/Users/matt/Younity/duxpoc/node_modules/dux-server/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/matt/Younity/duxpoc/node_modules/dux-server/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```
It places the binary into:
    'node-v0.11.14-darwin-x64' 
but it is being looked for in:
    'node-v11-darwin-x64'

When copying the binary to the location it is being looked for in, I then get this error:
```
 dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /Users/matt/Younity/duxpoc/node_modules/dux-server/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node
  Expected in: dynamic lookup
```

If somebody could look into this or point me in the right direction to resolving it myself, that would be awesome and much appreciated. We have a lot of code written to use this implementation so it'd be far from ideal to have to switch db implementations. (We had been using node 0.10.36 before which worked fine, but being forced to upgrade to 0.11.14 to use self signed certificates called for a new build against 0.11.14, which has resulted in the broken sqlite3). Thank you.

**Comment by springmeyer** [comment]
@mattfrey  - this is a very old issue. Copying is NOT recommended and the error you are seeing is because copying is not going to work. As far as your overall issue:

   - use the latest node-sqlite3 release: `v3.0.8`
   - use node v0.12.x instead of v0.11.x (which is the unstable and now unmaintained node version)

If you do the two above things and still hit a problem after a fresh install please create a new issue and don't comment on this old issue since its unlikely I will see it.

**Comment by mattfrey** [comment]
Thanks for the lightning fast reply! Sorry for bringing up an old issue, I didn't want to create a new one when it is obviously so similar. I made a mistake, meant to say sqlite3 3.0.8, not 1.0.8. We tried initially with node 0.12.4 but this causes other severe issues that we would have to work through. I went ahead and tried with 0.12.4 again though to see if it would address this particular issue, and surprisingly it is still looking in:
'node-v11-darwin-x64'
 for node_sqlite3.node, but the actual file now exists in:
node-v14-darwin-x64

Which I find pretty odd on both counts. If you have any insights into this please let me know, I will continue beating my head against config options and trying different node versions etc for now.
