### ISSUE TITLE
sqlite3 doesn't compile with node v0.10.0

### ISSUE THREAD

**Issue by jbuck** [mapbox/node-sqlite3#123]
I currently get the following error:

```
Jons-MacBook-Pro:butter jon$ npm remove sqlite3
Jons-MacBook-Pro:butter jon$ npm install
npm http GET https://registry.npmjs.org/sqlite3/2.1.5
npm http 200 https://registry.npmjs.org/sqlite3/2.1.5
npm http GET https://registry.npmjs.org/sqlite3/-/sqlite3-2.1.5.tgz
npm http 200 https://registry.npmjs.org/sqlite3/-/sqlite3-2.1.5.tgz
npm WARN engine sqlite3@2.1.5: wanted: {"node":">= 0.6.13 && < 0.9.0"} (current: {"node":"v0.10.0","npm":"1.2.14"})

> sqlite3@2.1.5 install /Users/jon/Dropbox/Sites/butter/node_modules/sqlite3
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.0/node-v0.10.0.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.0/node-v0.10.0.tar.gz
  CC(target) Release/obj.target/sqlite3/deps/sqlite3/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:140:18: error: no matching function for call to 'uv_queue_work'
    int status = uv_queue_work(uv_default_loop(),
                 ^~~~~~~~~~~~~
/Users/jon/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from 'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument;
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
../src/database.cc:223:18: error: no matching function for call to 'uv_queue_work'
    int status = uv_queue_work(uv_default_loop(),
                 ^~~~~~~~~~~~~
/Users/jon/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from 'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument;
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
../src/database.cc:502:18: error: no matching function for call to 'uv_queue_work'
    int status = uv_queue_work(uv_default_loop(),
                 ^~~~~~~~~~~~~
/Users/jon/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from 'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument;
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
../src/database.cc:571:18: error: no matching function for call to 'uv_queue_work'
    int status = uv_queue_work(uv_default_loop(),
                 ^~~~~~~~~~~~~
/Users/jon/.node-gyp/0.10.0/deps/uv/include/uv.h:1397:15: note: candidate function not viable: no known conversion from 'void (uv_work_t *)' to 'uv_after_work_cb' (aka 'void (*)(uv_work_t *, int)') for 4th argument;
UV_EXTERN int uv_queue_work(uv_loop_t* loop, uv_work_t* req,
              ^
4 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 12.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jon/Dropbox/Sites/butter/node_modules/sqlite3
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok
npm WARN optional dep failed, continuing sqlite3@2.1.5
```
